/***************************************************************************************************************************/
-- Author: Cristiano Miranda
--
-- Description:
-- 	Produce a summary listing of revenue generated by a particular item, itemType, or customer
-- 
-- Parameters:
-- 
-- Sample Execution
-- 	Sql statement below
--
-- Results
-- 	David		Smith		$15
/***************************************************************************************************************************/
create or replace view TopCustomerRep as

select P.FirstName  as 'FirstName',
		 P.LastName   as 'LastName',
		 sum(S.Price) as 'Revenue'
		 
from Sales S, Person P, Auction A

where P.SSN = A.Monitor and A.AuctionID = S.AuctionID

group by A.Monitor;

Select FirstName, LastName, Revenue
from TopCustomerRep
where Revenue = (select max(revenue) from TopCustomerRep);