CREATE TABLE `bid` (
	`BidID` MEDIUMINT NOT NULL AUTO_INCREMENT,
	`CustomerID` varchar(9) NOT NULL,
	`AuctionID` int unsigned NULL DEFAULT NULL,
	`ItemID` int unsigned NOT NULL DEFAULT '0',
	`BidTime` DATETIME NOT NULL DEFAULT '0000-00-00 00:00:00',
	`BidPrice` DECIMAL(13,2) NULL DEFAULT NULL,
	`IsProxy` BIT(1) NOT NULL DEFAULT 0,
	PRIMARY KEY (`BidID`, `CustomerID`, `ItemID`),
	INDEX `ItemID` (`ItemID`),
	INDEX `AuctionID` (`AuctionID`),
	CONSTRAINT `bid_ibfk_1` FOREIGN KEY (`ItemID`) REFERENCES `item` (`ItemID`) ON UPDATE CASCADE ON DELETE NO ACTION,
	CONSTRAINT `bid_ibfk_2` FOREIGN KEY (`CustomerID`) REFERENCES `customer` (`CustomerID`) ON UPDATE CASCADE ON DELETE NO ACTION,
	CONSTRAINT `bid_ibfk_3` FOREIGN KEY (`AuctionID`) REFERENCES `auction` (`AuctionID`) ON UPDATE CASCADE ON DELETE NO ACTION
);