CREATE TABLE `Sales` (
	`BuyerID` varchar(11) NOT NULL,
	`SellerID` varchar(11) NOT NULL,
	`Price` DECIMAL(13,2) NOT NULL,
	`Date` DATETIME NOT NULL,
	`ItemID` INT(10) UNSIGNED NOT NULL,
	`AuctionID` INT(10) UNSIGNED NOT NULL DEFAULT '0',
	PRIMARY KEY (`AuctionID`),
	INDEX `BuyerID` (`BuyerID`),
	INDEX `SellerID` (`SellerID`),
	INDEX `ItemID` (`ItemID`),
	CONSTRAINT `sales_ibfk_1` FOREIGN KEY (`BuyerID`) REFERENCES `customer` (`CustomerID`) ON UPDATE CASCADE ON DELETE NO ACTION,
	CONSTRAINT `sales_ibfk_2` FOREIGN KEY (`SellerID`) REFERENCES `customer` (`CustomerID`) ON UPDATE CASCADE ON DELETE NO ACTION,
	CONSTRAINT `sales_ibfk_3` FOREIGN KEY (`AuctionID`) REFERENCES `auction` (`AuctionID`) ON UPDATE CASCADE ON DELETE NO ACTION,
	CONSTRAINT `sales_ibfk_4` FOREIGN KEY (`ItemID`) REFERENCES `item` (`ItemID`) ON UPDATE CASCADE ON DELETE NO ACTION
);