/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/8.0.28
 * Generated at: 2015-12-02 19:56:35 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;
import java.sql.*;

public final class EmployeeInformation_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("java.sql");
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
        throws java.io.IOException, javax.servlet.ServletException {

final java.lang.String _jspx_method = request.getMethod();
if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method) && !javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET POST or HEAD");
return;
}

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write('\r');
      out.write('\n');

String username = "";
if (session.getAttribute("login") != null) {
	username = session.getAttribute("login").toString();
}
else {
	out.println("Invalid session! You must log back into the system.");
	return;
}
final String JDBC_DRIVER = "com.mysql.jdbc.Driver";
final String DB_URL = "jdbc:mysql://localhost:3306/SilkRoad 5.0";
final String USER = "root";
final String PASS = "root";

// Code starts here
String sql = null;
Connection conn = null;
CallableStatement cs = null;
Statement	stmt = null;

try	{
	//Register JDBC driver
	Class.forName(JDBC_DRIVER).newInstance();

	// Open a connection
	conn = java.sql.DriverManager.getConnection(DB_URL, USER, PASS);
} catch(Exception e) {
	e.printStackTrace();
	out.print(e.toString());
}
finally{
	try {
		if (cs != null) {
			cs.close();
		}
		if (conn != null) {
			conn.close();
		}
	} catch (Exception e) {};
}



      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html lang=\"en\">\r\n");
      out.write("\t<head>\r\n");
      out.write("\t\t<meta charset=\"utf-8\">\r\n");
      out.write("\t\t\t<meta http-equiv=\"X-UA-Compatible\" content=\"IE=edge\">\r\n");
      out.write("\t\t\t\t<meta name=\"viewport\" content=\"width=device-width, initial-scale=1\">\r\n");
      out.write("\t\t\t\t\t<!-- The above 3 meta tags *must* come first in the head; any other head content must come *after* these tags -->\r\n");
      out.write("\t\t\t\t\t<title>Silk Road 5.0</title>\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t<!-- Bootstrap -->\r\n");
      out.write("\t\t\t\t\t<link href=\"css/bootstrap.min.css\" rel=\"stylesheet\">\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t\t");
      out.write("\r\n");
      out.write("\t\t\t\t\t\t<link href=\"css/responsive.bootstrap.min.css\" rel=\"stylesheet\" type=\"text/css\">\r\n");
      out.write("\t\t\t\t\t\t\t<link href=\"https://cdnjs.cloudflare.com/ajax/libs/bootstrap3-dialog/1.34.5/css/bootstrap-dialog.min.css\" rel=\"stylesheet\" type=\"text/css\" />\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t\t\t<!-- Our own custom css -->\r\n");
      out.write("\t\t\t\t\t\t\t<link href=\"css/stylesheet.css\" rel=\"stylesheet\" type=\"text/css\">\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t\t\t\t<!-- HTML5 shim and Respond.js for IE8 support of HTML5 elements and media queries -->\r\n");
      out.write("\t\t\t\t\t\t\t\t<!-- WARNING: Respond.js doesn't work if you view the page via file:// -->\r\n");
      out.write("\t\t\t\t\t\t\t\t<!--[if lt IE 9]>\r\n");
      out.write("\t\t\t\t\t\t\t\t<script src=\"https://oss.maxcdn.com/html5shiv/3.7.2/html5shiv.min.js\"></script>\r\n");
      out.write("\t\t\t\t\t\t\t\t<script src=\"https://oss.maxcdn.com/respond/1.4.2/respond.min.js\"></script>\r\n");
      out.write("\t\t\t\t\t\t\t\t<![endif]-->\r\n");
      out.write("\t\t\t\t\t\t\t\t<!-- jQuery (necessary for Bootstrap's JavaScript plugins) -->\r\n");
      out.write("\t\t\t\t\t\t\t\t<script src=\"js/jquery-1.11.3.min.js\"></script>\r\n");
      out.write("\t\t\t\t\t\t\t\t<script src=\"js/jquery.validate.js\"></script>\r\n");
      out.write("\t\t\t\t\t\t\t\t");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t\t\t\t<!-- Include all compiled plugins (below), or include individual files as needed -->\r\n");
      out.write("\t\t\t\t\t\t\t\t<script src=\"js/bootstrap.min.js\"></script>\r\n");
      out.write("\t\t\t\t\t\t\t\t<script src=\"https://cdnjs.cloudflare.com/ajax/libs/bootstrap3-dialog/1.34.5/js/bootstrap-dialog.min.js\"></script>\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t\t\t\t<script src=\"js/pattern.js\"></script>\r\n");
      out.write("\t\t\t\t\t\t\t\t<script src=\"js/script.js\"></script>\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t\t\t</head>\r\n");
      out.write("\t\t\t\t\t\t\t<nav class=\"navbar\">\r\n");
      out.write("\t\t\t\t\t\t\t\t<div class=\"container-fluid\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<!-- Brand and toggle get grouped for better mobile display -->\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<div class=\"navbar-header\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<button type=\"button\" class=\"navbar-toggle collapsed\" data-toggle=\"collapse\" data-target=\"#bs-example-navbar-collapse-1\" aria-expanded=\"false\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t<span class=\"sr-only\">Toggle navigation</span>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t<span class=\"icon-bar\"></span>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t<span class=\"icon-bar\"></span>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t<span class=\"icon-bar\"></span>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t</button>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t</div> <!-- navbar-header -->\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<!-- Collect the nav links, forms, and other content for toggling -->\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<div class=\"myNavbar\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<ul class=\"nav\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t<li class=\"floatLeft\"><a href=\"EmployeeSearch.jsp\">Search</a></li>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t<li class=\"floatLeft\"><a href=\"PostAuctionPage.jsp\">Completed</a></li>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t<li class=\"dropdown navbar-right\" style=\"padding-left:125px;\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t<a data-target=\"#collapseHelp\" data-toggle=\"collapse\">Help<span class=\"caret\"></span></a>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t<ul>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t<div id=\"collapseHelp\" class=\"dropdown-menu\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t<li><a href=\"javascript:showScreenHelp()\">Screens</a></li><br>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t<li><a href=\"javascript:showAuctionHelp()\">Auctions</a></li><br>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t</ul>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t</li>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t<li class=\"dropdown navbar-right\" style=\"padding-left:200px;\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t<a data-target=\"#collapseMenu\" data-toggle=\"collapse\" >Menu<span class=\"caret\"></span></a>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t<ul>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t<div id=\"collapseMenu\" class=\"dropdown-menu\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t<li><a href=\"javascript:showBestSellers()\">Best Sellers</a></li><br>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t<li><a href=\"javascript:showItemSuggestions()\">Item Suggestions</a></li><br>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t</ul>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t</li>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t</ul> <!-- .nav -->\r\n");
      out.write("\t\t\t\t\t\t\t\t\t</div> <!-- .myNavbar -->\r\n");
      out.write("\t\t\t\t\t\t\t\t</div> <!-- .container-fluid -->\r\n");
      out.write("\t\t\t\t\t\t\t</nav>\r\n");
      out.write("\t\t\t\t\t\t\t<body class=\"auctionHouseBody\">\r\n");
      out.write("\t\t\t\t\t\t\t\t<div class=\"container\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<h2 align=\"center\" style=\"font-size:28px\">Customer-Representative Actions</h2> <br><br>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<a href=\"RecordSale.jsp\" style=\"font-size : 28px;\" class=\"btn btn-default btn-block\">Record a Sale</a><hr>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<a href=\"EditCustomer.jsp\" style=\"font-size : 28px;\" class=\"btn btn-primary btn-block\">Edit Customer Data</a><hr>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<a href=\"MailingList.jsp\" style=\"font-size : 28px;\" class=\"btn btn-success btn-block\">Customer Mailing List</a><hr>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<a href=\"SuggestCustomerItem.jsp\" style=\"font-size : 28px;\" class=\"btn btn-info btn-block\"   >Customer Item Suggestions</a>\r\n");
      out.write("\t\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t</body>\r\n");
      out.write("\t\t\t\t\t\t</html>\r\n");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
